# Examining Socioeconomic Factors Associated with Diabetes Using NHANES Data

## Introduction

Understanding the relationship between these socioeconomic factors and diabetes prevalence is essential for developing targeted prevention strategies. We use data from the National Health and Nutrition Examination Survey (NHANES) to explore the relationship between diabetes status and socioeconomic factors using multinomial logistic regression.

## Data

NHANES is a nationally representative cross-sectional survey conducted by the Centers for Disease Control and Prevention (CDC). It combines interviews, physical examinations, and laboratory measurements. For detailed information, you can refer to the website: https://wwwn.cdc.gov/nchs/nhanes/

For this analysis, we used the following NHANES components:

1). Education level and income-to-poverty ratio from Demographics data (`data/DEMO_L.xpt`).

2). Diabetes status from Diabetes Questionnaire data (`data/DIQ_L.xtp`).

## Repository Structure

```
┌── data/                         # Raw data and saved cleaned dataset
│   ├── DEMO_L.xpt                # Demographics data from NHANES (education, income-to-poverty ratio)
│   ├── DIQ_L.xpt                 # Diabetes Questionnaire data from NHANES
│   └── clean.RData               # Cleaned and merged dataset ready for analysis
├── source/                       # Modular scripts for cleaning, analysis, and visualization
│   ├── data_cleaning.R           # Data cleaning and preprocessing script
│   ├── data_analysis.R           # Multinomial logistic regression model fitting
│   └── data_visualization.R      # Code for generating figures
├── analysis/                 # Contain all the source R Markdown files that implement the analyses for the project
│   ├── final_report.Rmd          # Main R Markdown file for the complete analysis report  
|   └── final_report.pdf          # PDF output generated by knitting final_report.Rmd
├── README.md                     # Project overview and reproduction instructions
└── results/                      # Contain results exported by the analysis files
    └──  figure-1.png             # Visualization of analysis summary
```

## Session Information

```
R version 4.3.2 (2023-10-31)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS 15.6.1

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.11.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: America/New_York
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] gridExtra_2.3 ggplot2_3.5.2 dplyr_1.1.4   here_1.0.1    haven_2.5.4   nnet_7.3-19  

loaded via a namespace (and not attached):
 [1] gtable_0.3.4      compiler_4.3.2    tidyselect_1.2.1  scales_1.3.0      yaml_2.3.8        fastmap_1.1.1    
 [7] readr_2.1.5       R6_2.6.1          labeling_0.4.3    generics_0.1.3    knitr_1.45        forcats_1.0.0    
[13] tibble_3.2.1      munsell_0.5.0     rprojroot_2.0.4   pillar_1.9.0      tzdb_0.4.0        rlang_1.1.5      
[19] utf8_1.2.4        xfun_0.41         cli_3.6.4         withr_3.0.0       magrittr_2.0.3    digest_0.6.37    
[25] grid_4.3.2        rstudioapi_0.15.0 hms_1.1.3         lifecycle_1.0.4   vctrs_0.6.5       evaluate_0.23    
[31] glue_1.8.0        farver_2.1.1      fansi_1.0.6       colorspace_2.1-1  rmarkdown_2.25    tools_4.3.2      
[37] pkgconfig_2.0.3   htmltools_0.5.8.1
```

## Reproduction Instructions

To reproduce this analysis, follow these steps:

1). Clone this repository to your local machine and open the RStudio project file (`.Rproj`).

2). Install all required R packages listed in the Session Information section above.

3). Open `analysis/final_report.Rmd` and knit the file to HTML format.


## Collaboration Note

The NHANES dataset selection and initial data identification were conducted collaboratively with another student Rita Zhirui Fu. However, the research question, analysis, and interpretation presented in this repository are entirely independent and unique to this project.
